### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by blephy** [joaner/html-webpack-preconnect-plugin#1]
Hi,

Tried your plugin with webpack 4.29.5 and html-webpack-plugin 3.2.0.

The webpack plugins config section : 

```js
{
    ...
    new HtmlWebPackPlugin({
      meta: configInstance.config.html.meta,
      title: configInstance.config.html.title,
      template: configInstance.path.html,
      filename: 'index.html',
      favicon: configInstance.favicon,
      minify: true,
      xhtml: true,
      preconnect: [`https://${configInstance.env.apiBaseUrl}`]
    }),
    new HtmlWebpackPreconnectPlugin(),
    ...
}
```

The broken output html file content : 

```html
Html Webpack Plugin:
<pre>
  TypeError: callback is not a function
  
  - index.js:39 
    [*********]/[html-webpack-preconnect-plugin]/index.js:39:7
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [*********]/[html-webpack-plugin]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 
    [*********]/[html-webpack-plugin]/index.js:673:47
  
  - index.js:187 Promise.resolve.then.then.then.then.then.then.then.result
    [*********]/[html-webpack-plugin]/index.js:187:18
  
  - next_tick.js:77 process.internalTickCallback
    internal/process/next_tick.js:77:7
  
</pre>
```

Any idea ?

**Comment by joaner** [comment]
sorry, this project only support webpack 3.x, not supported webpack 4.x.
A few days later I will develop a version of webpack4, there is no solution, sorry.

**Comment by blephy** [comment]
No problem ;)

Let me know about, is this is because of new hooks api ?

**Comment by michellocana** [comment]
@joaner i'm looking for webpack 4 support too, i can open a PR if it's ok to you :)

**Comment by joaner** [comment]
@michellocana  Sure, thank you very much!
I haven't developed webpack 4 support yet. It is great to have your help.

**Comment by michellocana** [comment]
@joaner cool, i will give it a try! probably we gonna need some refactor in the tests setup to be able to run tests both in webpack 3 and 4, but no problem 😄

**Comment by joaner** [comment]
Thank @michellocana very much, I tested your code and worked perfectly. The new version `1.1.0` that supports webpack4 has been released. Thank you for your contribution.

**Comment by joaner** [comment]
@blephy Let you wait for me, I had difficulties in the development process, but finally solved by michellocana.
you could install version 1.1.0 for webpack 3/4 support, thanks.

**Comment by blephy** [comment]
Ty @joaner  !

**Comment by joaner** [comment]
thanks guys
