### ISSUE TITLE
Plugin not working with html-webpack-plugin 4 (beta)

### ISSUE THREAD

**Issue by vmkarpenko** [joaner/html-webpack-preconnect-plugin#4]
tapAsync undefined

compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync('htmlWebpackPreconnectPlugin', addPreconnectLinks)

**Comment by vitaliyhayda** [comment]
Same issue with a non-beta webpack

**Comment by joaner** [comment]
I released a new version v1.2.0 #6  to compatible with html-webpack-plugin v4, thanks for your feedback.
